packages:
  - coreply-app
  - coreply-wrapper
  - libcoreply
  - coreply-shared-components
  - coreply-browser-extension
allowBuilds:
  esbuild: true
  spawn-sync: true
minimumReleaseAgeExclude:
  - expo-brownfield@56.0.21
  - expo-build-properties@56.0.20
