export const SUPPORTED_APPS = [
  "com.whatsapp.w4b",
  "jp.naver.line.android",
  "com.instagram.android",
  "org.thoughtcrime.securesms",
  "co.hinge.app",
  "com.tinder",
  "com.vr.heymandi",
  "com.android.systemui",
  "com.whatsapp",
  "org.telegram.messenger",
  "org.telegram.messenger.web",
  "tw.nekomimi.nekogram",
  "com.mattermost.rn",
  "com.google.android.apps.messaging",
  "com.facebook.orca",
  "com.snapchat.android",
  "com.microsoft.teams",
  "com.viber.voip",
  "com.discord",
  "com.beeper.android",
  "com.openai.chatgpt",
  "ai.perplexity.app.android",
] as const;

export const SUPPORTED_APP_SET = new Set<string>(SUPPORTED_APPS);
